# data_dir: '/home/andyb/project_in_bioinformatics/data'
data_dir: '/home/andrej/ActiveProjects/project_in_bioinformatics/data'
# study: ["TCGA", "GTEx"]
study: ['TCGA', 'GTEx']
# type: ["gene", "exon"]
type: ['gene']
# size: ["full", "subset"]
size: ["200x100"]
#
filter: ["pca", "naive"]
#
# hidden: ["0", "1"]
# predictors: ["9662"]
# predictors: ["50"]
architecture: ["50-50"]
#
max_training_time: "60"
